name: fluttermovie
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  flutter_map: ^5.0.0
  equatable: ^2.0.5
  dio: ^5.3.2
  flutter_svg: ^2.0.7
  sqflite: ^2.3.0
  path: ^1.8.3
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  permission_handler: ^10.4.3
  geolocator: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
